name: Labeler🏷️
on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213
        with:
          repo-token: "${{ secrets.GH_TOKEN }}"
          sync-labels: true
